name: 'Build Docker Image'
description: 'Build and verify Brainsmith Docker image'

runs:
  using: 'composite'
  steps:
    - name: Build and verify Docker image
      shell: bash
      run: |
        chmod +x ctl-docker.sh
        echo "=== Building Docker image ==="
        ./ctl-docker.sh build
        
        echo "=== Verifying image was built ==="
        echo "Expected image tag: $BSMITH_DOCKER_TAG"
        
        # Wait a moment for Docker to register the image
        sleep 2
        
        # Show all docker images for debugging
        echo "All Docker images:"
        docker images
        
        # Check for the specific tag
        if docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "microsoft/brainsmith:"; then
            echo "✓ Docker image built and verified successfully"
        else
            echo "ERROR: Docker image not found after build"
            echo "Looking for images matching: microsoft/brainsmith:"
            docker images | grep "microsoft/brainsmith" || echo "No matching images found"
            exit 1
        fi