// Auto-generated by Brainsmith Kernel Integrator
// Generated from: brainsmith/kernels/thresholding/thresholding_axi_bw.sv
// Date: 2025-08-21T22:53:30.571428

module thresholding_axi_wrapper #(
    // General algorithm parameters
    parameter input_FPARG = $INPUT_FPARG$,
    parameter BIAS = $BIAS$,
    parameter THRESHOLDS_PATH = $THRESHOLDS_PATH$,
    parameter DEPTH_TRIGGER_URAM = $DEPTH_TRIGGER_URAM$,
    parameter DEPTH_TRIGGER_BRAM = $DEPTH_TRIGGER_BRAM$,
    parameter DEEP_PIPELINE = $DEEP_PIPELINE$,
    // AXI-Lite configuration parameter
    parameter USE_AXILITE = $USE_AXILITE$,
    // threshold datatype
    parameter T_WIDTH = $T_WIDTH$,
    // input interface parameters
    parameter input_BDIM = $INPUT_BDIM$,
    parameter input_SDIM = $INPUT_SDIM$,
    parameter input_WIDTH = $INPUT_WIDTH$,
    parameter input_SIGNED = $INPUT_SIGNED$,
    // output interface parameters
    parameter output_WIDTH = $OUTPUT_WIDTH$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    // input: INPUT interface
    input wire [$INPUT_STREAM_WIDTH$-1:0] input_TDATA,
    input wire input_TVALID,
    output wire input_TREADY,
    // output: OUTPUT interface
    output wire [$OUTPUT_STREAM_WIDTH$-1:0] output_TDATA,
    output wire output_TVALID,
    input wire output_TREADY,
    // threshold: CONFIG interface (AXI-Lite)
    // Write Address Channel
    input wire threshold_AWVALID,
    output wire threshold_AWREADY,
    input wire [31:0] threshold_AWADDR,
    // Write Data Channel
    input wire threshold_WVALID,
    output wire threshold_WREADY,
    input wire [31:0] threshold_WDATA,
    input wire [3:0] threshold_WSTRB,

    // Write Response Channel
    output wire threshold_BVALID,
    input wire threshold_BREADY,
    output wire [1:0] threshold_BRESP,
    // Read Address Channel
    input wire threshold_ARVALID,
    output wire threshold_ARREADY,
    input wire [31:0] threshold_ARADDR,
    // Read Data Channel
    output wire threshold_RVALID,
    input wire threshold_RREADY,
    output wire [31:0] threshold_RDATA,
    output wire [1:0] threshold_RRESP);

    // Instantiate the wrapped kernel
    thresholding_axi #(        // General algorithm parameters
        .input_FPARG(input_FPARG),
        .BIAS(BIAS),
        .THRESHOLDS_PATH(THRESHOLDS_PATH),
        .DEPTH_TRIGGER_URAM(DEPTH_TRIGGER_URAM),
        .DEPTH_TRIGGER_BRAM(DEPTH_TRIGGER_BRAM),
        .DEEP_PIPELINE(DEEP_PIPELINE),
        // AXI-Lite configuration parameters
        .USE_AXILITE(USE_AXILITE),
        // threshold datatype
        .T_WIDTH(T_WIDTH),
        // input interface parameters
        .input_BDIM(input_BDIM),
        .input_SDIM(input_SDIM),
        .input_WIDTH(input_WIDTH),
        .input_SIGNED(input_SIGNED),
        // output interface parameters
        .output_WIDTH(output_WIDTH)    ) thresholding_axi_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        // input connections
        .input_tdata(input_TDATA),
        .input_tvalid(input_TVALID),
        .input_tready(input_TREADY),
        // output connections  
        .output_tdata(output_TDATA),
        .output_tvalid(output_TVALID),
        .output_tready(output_TREADY),
        // threshold connections
        .threshold_AWVALID(threshold_AWVALID),
        .threshold_AWREADY(threshold_AWREADY),
        .threshold_AWADDR(threshold_AWADDR),
        .threshold_WVALID(threshold_WVALID),
        .threshold_WREADY(threshold_WREADY),
        .threshold_WDATA(threshold_WDATA),
        .threshold_WSTRB(threshold_WSTRB),
        .threshold_BVALID(threshold_BVALID),
        .threshold_BREADY(threshold_BREADY),
        .threshold_BRESP(threshold_BRESP),
        .threshold_ARVALID(threshold_ARVALID),
        .threshold_ARREADY(threshold_ARREADY),
        .threshold_ARADDR(threshold_ARADDR),
        .threshold_RVALID(threshold_RVALID),
        .threshold_RREADY(threshold_RREADY),
        .threshold_RDATA(threshold_RDATA),
        .threshold_RRESP(threshold_RRESP)    );

endmodule // thresholding_axi_wrapper