# Auto-generated by Brainsmith Hardware Kernel Generator
# Generated from: test_new_pragma_format.sv
# Date: 2025-06-16T23:25:42.368071

from brainsmith.dataflow.core.auto_rtl_backend import AutoRTLBackend
from qonnx.core.datatype import DataType


class test_new_format_rtl(AutoRTLBackend):
    """RTL backend for test_new_format operation.
    
    Auto-generated from SystemVerilog RTL analysis.
    
    Hardware accelerator operation: test_new_format
    """
    
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)
    
    @property
    def finn_rtllib_module(self) -> str:
        """Return finn-rtllib module name for this operation."""
        return "test_new_format"
    
    def get_nodeattr_types(self):
        """Get node attribute types for RTLBackend (algorithm parameters only)."""
        my_attrs = {}
        
        # Only expose algorithm parameters, NOT datatype-linked parameters
        # Algorithm parameter - optional with default
        my_attrs["INPUT0_BDIM"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["INPUT0_SDIM"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["OUTPUT0_BDIM"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["OUTPUT0_SDIM"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["C"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["PE"] = ("i", False, 4)
        
        # Merge with parent class attributes
        my_attrs.update(AutoRTLBackend.get_nodeattr_types(self))
        
        return my_attrs
    
    def prepare_codegen_rtl_values(self, model):
        """Prepare template variables for RTL code generation.
        
        All dictionary values produced in this function are to replace
        their key value(s) in the RTL template files following FINN's pattern.
        """
        code_gen_dict = {}
        
        # Basic module information
        code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"] = [self.get_verilog_top_module_name()]
        code_gen_dict["$TOP_MODULE$"] = code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"]
        
        # Standard stream width variables
        code_gen_dict["$IBITS$"] = [str(self.get_instream_width())]
        code_gen_dict["$OBITS$"] = [str(self.get_outstream_width())]
        
        # Algorithm parameters from node attributes
        code_gen_dict["$INPUT0_BDIM$"] = [str(self.get_nodeattr("INPUT0_BDIM"))]
        code_gen_dict["$INPUT0_SDIM$"] = [str(self.get_nodeattr("INPUT0_SDIM"))]
        code_gen_dict["$OUTPUT0_BDIM$"] = [str(self.get_nodeattr("OUTPUT0_BDIM"))]
        code_gen_dict["$OUTPUT0_SDIM$"] = [str(self.get_nodeattr("OUTPUT0_SDIM"))]
        code_gen_dict["$C$"] = [str(self.get_nodeattr("C"))]
        code_gen_dict["$PE$"] = [str(self.get_nodeattr("PE"))]
        
        # Datatype-linked parameters computed on-demand
        # Generic datatype-linked parameter
        code_gen_dict["$INPUT0_WIDTH$"] = [str(self.get_nodeattr("INPUT0_WIDTH") if "INPUT0_WIDTH" in str(self.get_nodeattr_types()) else 1)]
        # Generic datatype-linked parameter
        code_gen_dict["$OUTPUT0_WIDTH$"] = [str(self.get_nodeattr("OUTPUT0_WIDTH") if "OUTPUT0_WIDTH" in str(self.get_nodeattr_types()) else 1)]
        # Generic datatype-linked parameter
        code_gen_dict["$SIGNED_INPUT0$"] = [str(self.get_nodeattr("SIGNED_INPUT0") if "SIGNED_INPUT0" in str(self.get_nodeattr_types()) else 1)]
        # Generic datatype-linked parameter
        code_gen_dict["$SIGNED_OUTPUT0$"] = [str(self.get_nodeattr("SIGNED_OUTPUT0") if "SIGNED_OUTPUT0" in str(self.get_nodeattr_types()) else 1)]
        
        return code_gen_dict
    
    def get_supporting_rtl_files(self) -> list:
        """Get list of supporting RTL files to include."""
        return [
            "test_new_format_axi.sv",
            "test_new_format.sv",
        ]
    
    def lut_estimation(self) -> int:
        """Estimate LUT usage for test_new_format."""
        # TODO: Implement operation-specific LUT estimation
        # For now, use base class conservative estimate
        return super().lut_estimation()
    
    def bram_estimation(self) -> int:
        """Estimate BRAM usage for test_new_format."""
        # TODO: Implement operation-specific BRAM estimation
        # For now, use base class estimate
        return super().bram_estimation()
    
    def dsp_estimation(self, fpgapart) -> int:
        """Estimate DSP usage for test_new_format."""
        # TODO: Implement operation-specific DSP estimation
        # For now, use base class estimate
        return super().dsp_estimation(fpgapart)
