// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: test_new_pragma_format.sv
// Date: 2025-06-16T23:25:42.380479

module test_new_format_wrapper #(
    // Parameters from original module
    parameter INPUT0_WIDTH = $INPUT0_WIDTH$,
    parameter SIGNED_INPUT0 = $SIGNED_INPUT0$,
    parameter OUTPUT0_WIDTH = $OUTPUT0_WIDTH$,
    parameter INPUT0_BDIM = $INPUT0_BDIM$,
    parameter INPUT0_SDIM = $INPUT0_SDIM$,
    parameter OUTPUT0_BDIM = $OUTPUT0_BDIM$,
    parameter OUTPUT0_SDIM = $OUTPUT0_SDIM$,
    parameter C = $C$,
    parameter PE = $PE$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // s_axis_input0: INPUT interface
    input wire [s_axis_input0_TDATA_WIDTH-1:0] s_axis_input0_TDATA,
    input wire s_axis_input0_TVALID,
    output wire s_axis_input0_TREADY,
    // m_axis_output0: OUTPUT interface
    output wire [m_axis_output0_TDATA_WIDTH-1:0] m_axis_output0_TDATA,
    output wire m_axis_output0_TVALID,
    input wire m_axis_output0_TREADY);

    // Instantiate the wrapped kernel
    test_new_format #(
        // Pass parameters
        .INPUT0_WIDTH(INPUT0_WIDTH),
        .SIGNED_INPUT0(SIGNED_INPUT0),
        .OUTPUT0_WIDTH(OUTPUT0_WIDTH),
        .INPUT0_BDIM(INPUT0_BDIM),
        .INPUT0_SDIM(INPUT0_SDIM),
        .OUTPUT0_BDIM(OUTPUT0_BDIM),
        .OUTPUT0_SDIM(OUTPUT0_SDIM),
        .C(C),
        .PE(PE)    ) test_new_format_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // s_axis_input0 connections
        .s_axis_input0_TDATA(s_axis_input0_TDATA),
        .s_axis_input0_TVALID(s_axis_input0_TVALID),
        .s_axis_input0_TREADY(s_axis_input0_TREADY),
        // m_axis_output0 connections
        .m_axis_output0_TDATA(m_axis_output0_TDATA),
        .m_axis_output0_TVALID(m_axis_output0_TVALID),
        .m_axis_output0_TREADY(m_axis_output0_TREADY)    );

endmodule // test_new_format_wrapper