// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: multi_input_test.sv
// Date: 2025-06-15T18:28:33.186730

module multi_input_add_wrapper #(
    // Parameters from original module
    parameter INPUT0_WIDTH = $INPUT0_WIDTH$,
    parameter SIGNED_INPUT0 = $SIGNED_INPUT0$,
    parameter INPUT1_WIDTH = $INPUT1_WIDTH$,
    parameter SIGNED_INPUT1 = $SIGNED_INPUT1$,
    parameter OUTPUT_WIDTH = $OUTPUT_WIDTH$,
    parameter SIGNED_OUTPUT = $SIGNED_OUTPUT$,
    parameter ALGORITHM_PARAM = $ALGORITHM_PARAM$,
    parameter PE = $PE$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // s_axis_input0: INPUT interface
    input wire [s_axis_input0_TDATA_WIDTH-1:0] s_axis_input0_TDATA,
    input wire s_axis_input0_TVALID,
    output wire s_axis_input0_TREADY,    // s_axis_input1: INPUT interface
    input wire [s_axis_input1_TDATA_WIDTH-1:0] s_axis_input1_TDATA,
    input wire s_axis_input1_TVALID,
    output wire s_axis_input1_TREADY,
    // m_axis_output0: OUTPUT interface
    output wire [m_axis_output0_TDATA_WIDTH-1:0] m_axis_output0_TDATA,
    output wire m_axis_output0_TVALID,
    input wire m_axis_output0_TREADY);

    // Instantiate the wrapped kernel
    multi_input_add #(
        // Pass parameters
        .INPUT0_WIDTH(INPUT0_WIDTH),
        .SIGNED_INPUT0(SIGNED_INPUT0),
        .INPUT1_WIDTH(INPUT1_WIDTH),
        .SIGNED_INPUT1(SIGNED_INPUT1),
        .OUTPUT_WIDTH(OUTPUT_WIDTH),
        .SIGNED_OUTPUT(SIGNED_OUTPUT),
        .ALGORITHM_PARAM(ALGORITHM_PARAM),
        .PE(PE)    ) multi_input_add_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // s_axis_input0 connections
        .s_axis_input0_TDATA(s_axis_input0_TDATA),
        .s_axis_input0_TVALID(s_axis_input0_TVALID),
        .s_axis_input0_TREADY(s_axis_input0_TREADY),        // s_axis_input1 connections
        .s_axis_input1_TDATA(s_axis_input1_TDATA),
        .s_axis_input1_TVALID(s_axis_input1_TVALID),
        .s_axis_input1_TREADY(s_axis_input1_TREADY),
        // m_axis_output0 connections
        .m_axis_output0_TDATA(m_axis_output0_TDATA),
        .m_axis_output0_TVALID(m_axis_output0_TVALID),
        .m_axis_output0_TREADY(m_axis_output0_TREADY)    );

endmodule // multi_input_add_wrapper