############################################################################
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# @author       Thomas Keller <thomaskeller@microsoft.com>
############################################################################
"""
Auto-generated thresholding HWCustomOp package.

This package contains FINN-compatible implementations generated by the
Hardware Kernel Generator from SystemVerilog RTL.
"""