name: 'Docker Execute'
description: 'Execute commands in ctl-docker.sh container with lifecycle management'
inputs:
  command:
    description: 'Command to execute in the container'
    type: string
    required: true
  timeout-minutes:
    description: 'Command timeout in minutes'
    type: number
    default: 60

runs:
  using: 'composite'
  steps:
    - name: Execute command with ctl-docker.sh
      shell: bash
      run: |
        echo "=== Executing: ${{ inputs.command }} ==="
        echo "Timeout: ${{ inputs.timeout-minutes }} minutes"
        
        # Make ctl-docker.sh executable
        chmod +x ctl-docker.sh
        
        # Start container using ctl-docker.sh
        echo "Starting container..."
        ./ctl-docker.sh start
        
        # Wait for container to be ready
        echo "Waiting for container to be ready..."
        sleep 5
        
        # Execute command with timeout
        TIMEOUT_SECONDS=$(( ${{ inputs.timeout-minutes }} * 60 ))
        
        if timeout ${TIMEOUT_SECONDS}s ./ctl-docker.sh "${{ inputs.command }}"; then
            echo "✓ Command executed successfully"
            EXIT_CODE=0
        else
            echo "✗ Command failed or timed out"
            echo "=== Container logs (last 50 lines) ==="
            ./ctl-docker.sh logs --tail 50 || echo "No logs available"
            EXIT_CODE=1
        fi
        
        # Always stop container
        echo "Stopping container..."
        ./ctl-docker.sh stop || true
        
        exit $EXIT_CODE