name: 'Smithy Test'
description: 'Run test with smithy container using predefined commands'
inputs:
  test-name:
    description: 'Name of the test'
    type: string
    required: true
  test-type:
    description: 'Type of test to run'
    type: string
    required: true
    # Valid options: e2e-bert, unit-tests, integration-tests, basic-functionality
  test-variant:
    description: 'Test variant'
    type: string
    default: 'default'
    # Valid options: default, clean, large, small
  timeout-minutes:
    description: 'Test timeout in minutes'
    type: number
    default: 60

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        # Validate test name
        if ! [[ "${{ inputs.test-name }}" =~ ^[a-zA-Z0-9\ \-]+$ ]]; then
            echo "ERROR: Invalid test name format"
            exit 1
        fi
        
        # Validate timeout
        if [ "${{ inputs.timeout-minutes }}" -le 0 ] || [ "${{ inputs.timeout-minutes }}" -gt 1440 ]; then
            echo "ERROR: Invalid timeout value (must be 1-1440 minutes)"
            exit 1
        fi
        
        echo "✓ Input validation passed"
    
    - name: Determine test command
      shell: bash
      id: test-cmd
      run: |
        case "${{ inputs.test-type }}" in
          "e2e-bert")
            case "${{ inputs.test-variant }}" in
              "default") COMMAND="cd demos/bert && make clean && make" ;;
              "large") COMMAND="cd demos/bert && make bert_large_single_layer" ;;
              "clean") COMMAND="cd demos/bert && make clean" ;;
              *) echo "ERROR: Invalid bert variant"; exit 1 ;;
            esac
            ;;
          "unit-tests")
            COMMAND="cd tests && pytest -v ./"
            ;;
          "integration-tests")
            COMMAND="cd tests && pytest -v integration/"
            ;;
          "basic-functionality")
            COMMAND="python -c 'import sys; import brainsmith; import finn; import qonnx; print(\"✓ All critical imports successful\"); print(f\"Python: {sys.version}\"); print(f\"Brainsmith: OK\"); print(f\"FINN: OK\"); print(f\"QONNX: OK\")'"
            ;;
          *)
            echo "ERROR: Invalid test type. Allowed: e2e-bert, unit-tests, integration-tests, basic-functionality"
            exit 1
            ;;
        esac
        
        echo "test-command=$COMMAND" >> $GITHUB_OUTPUT
        echo "✓ Test command determined: $COMMAND"
    
    - name: Configure for local image
      shell: bash
      run: |
        # Ensure smithy uses locally available image
        export BSMITH_DOCKER_PREBUILT="1"
        echo "BSMITH_DOCKER_PREBUILT=1" >> $GITHUB_ENV
        
        # Verify image is available locally
        if ! docker images | grep -q "microsoft/brainsmith"; then
            echo "ERROR: Brainsmith image not available locally"
            echo "Available images:"
            docker images
            exit 1
        fi
        echo "✓ Local image verified"
    
    - name: Run smithy test
      shell: bash
      run: |
        echo "=== Running test: ${{ inputs.test-name }} ==="
        echo "Test type: ${{ inputs.test-type }}"
        echo "Test variant: ${{ inputs.test-variant }}"
        echo "Command: ${{ steps.test-cmd.outputs.test-command }}"
        echo "Timeout: ${{ inputs.timeout-minutes }} minutes"
        
        # Verify daemon is running (should be started by workflow)
        # Use a simple test command to check if container is accessible
        if ! ./smithy exec "echo 'Container is accessible'" >/dev/null 2>&1; then
            echo "ERROR: Smithy daemon is not running or not accessible"
            echo "The daemon should be started by the workflow before running tests"
            echo "Current status:"
            ./smithy status || echo "Status command failed"
            echo "Debug: Attempting to list running containers:"
            docker ps --filter "name=brainsmith" || echo "Docker ps failed"
            exit 1
        fi
        echo "✓ Daemon is running and accessible - proceeding with test"
        
        # Execute test with timeout using existing daemon
        TIMEOUT_SECONDS=$(( ${{ inputs.timeout-minutes }} * 60 ))
        
        if timeout ${TIMEOUT_SECONDS}s ./smithy exec "${{ steps.test-cmd.outputs.test-command }}"; then
            echo "✓ Test passed: ${{ inputs.test-name }}"
        else
            echo "✗ Test failed: ${{ inputs.test-name }}"
            echo "=== Container logs (last 50 lines) ==="
            ./smithy logs --tail 50 || echo "No logs available"
            exit 1
        fi