name: 'Docker Load'
description: 'Load Docker image from artifact'
inputs:
  artifact-name:
    description: 'Artifact name for saved image'
    type: string
    default: 'docker-image'
  image-tag:
    description: 'Expected image tag after load'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/docker-artifacts
    
    - name: Load Docker image
      shell: bash
      run: |
        echo "=== Loading Docker image ==="
        ARTIFACT_NAME="${{ inputs.artifact-name }}"
        EXPECTED_TAG="${{ inputs.image-tag }}"
        
        # Verify artifact exists
        if [ ! -f "/tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz" ]; then
            echo "ERROR: Artifact file not found"
            ls -la /tmp/docker-artifacts/
            exit 1
        fi
        
        # Load image
        echo "Loading image from artifact..."
        docker load < "/tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz"
        
        # Verify loaded image
        if ! docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^${EXPECTED_TAG}$"; then
            echo "ERROR: Expected image ${EXPECTED_TAG} not found after load"
            echo "Available images:"
            docker images
            exit 1
        fi
        
        echo "✓ Image loaded successfully: ${EXPECTED_TAG}"
        docker images | grep "microsoft/brainsmith"