// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: brainsmith/hw_kernels/thresholding/thresholding_axi.sv
// Date: 2025-06-16T22:42:52.262395

module thresholding_axi_wrapper #(
    // Parameters from original module
    parameter N = $N$,
    parameter WI = $WI$,
    parameter WT = $WT$,
    parameter C = $C$,
    parameter PE = $PE$,
    parameter SIGNED = $SIGNED$,
    parameter FPARG = $FPARG$,
    parameter BIAS = $BIAS$,
    parameter THRESHOLDS_PATH = $THRESHOLDS_PATH$,
    parameter USE_AXILITE = $USE_AXILITE$,
    parameter DEPTH_TRIGGER_URAM = $DEPTH_TRIGGER_URAM$,
    parameter DEPTH_TRIGGER_BRAM = $DEPTH_TRIGGER_BRAM$,
    parameter DEEP_PIPELINE = $DEEP_PIPELINE$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // s_axis: INPUT interface
    input wire [s_axis_TDATA_WIDTH-1:0] s_axis_TDATA,
    input wire s_axis_TVALID,
    output wire s_axis_TREADY,
    // m_axis: OUTPUT interface
    output wire [m_axis_TDATA_WIDTH-1:0] m_axis_TDATA,
    output wire m_axis_TVALID,
    input wire m_axis_TREADY,
    // s_axilite: CONFIG interface (AXI-Lite)
    input wire s_axilite_AWVALID,
    output wire s_axilite_AWREADY,
    input wire [31:0] s_axilite_AWADDR,
    input wire s_axilite_WVALID,
    output wire s_axilite_WREADY,
    input wire [31:0] s_axilite_WDATA,
    input wire [3:0] s_axilite_WSTRB,
    output wire s_axilite_BVALID,
    input wire s_axilite_BREADY,
    output wire [1:0] s_axilite_BRESP,
    input wire s_axilite_ARVALID,
    output wire s_axilite_ARREADY,
    input wire [31:0] s_axilite_ARADDR,
    output wire s_axilite_RVALID,
    input wire s_axilite_RREADY,
    output wire [31:0] s_axilite_RDATA,
    output wire [1:0] s_axilite_RRESP);

    // Instantiate the wrapped kernel
    thresholding_axi #(
        // Pass parameters
        .N(N),
        .WI(WI),
        .WT(WT),
        .C(C),
        .PE(PE),
        .SIGNED(SIGNED),
        .FPARG(FPARG),
        .BIAS(BIAS),
        .THRESHOLDS_PATH(THRESHOLDS_PATH),
        .USE_AXILITE(USE_AXILITE),
        .DEPTH_TRIGGER_URAM(DEPTH_TRIGGER_URAM),
        .DEPTH_TRIGGER_BRAM(DEPTH_TRIGGER_BRAM),
        .DEEP_PIPELINE(DEEP_PIPELINE)    ) thresholding_axi_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // s_axis connections
        .s_axis_TDATA(s_axis_TDATA),
        .s_axis_TVALID(s_axis_TVALID),
        .s_axis_TREADY(s_axis_TREADY),
        // m_axis connections
        .m_axis_TDATA(m_axis_TDATA),
        .m_axis_TVALID(m_axis_TVALID),
        .m_axis_TREADY(m_axis_TREADY),
        // s_axilite connections
        .s_axilite_AWVALID(s_axilite_AWVALID),
        .s_axilite_AWREADY(s_axilite_AWREADY),
        .s_axilite_AWADDR(s_axilite_AWADDR),
        .s_axilite_WVALID(s_axilite_WVALID),
        .s_axilite_WREADY(s_axilite_WREADY),
        .s_axilite_WDATA(s_axilite_WDATA),
        .s_axilite_WSTRB(s_axilite_WSTRB),
        .s_axilite_BVALID(s_axilite_BVALID),
        .s_axilite_BREADY(s_axilite_BREADY),
        .s_axilite_BRESP(s_axilite_BRESP),
        .s_axilite_ARVALID(s_axilite_ARVALID),
        .s_axilite_ARREADY(s_axilite_ARREADY),
        .s_axilite_ARADDR(s_axilite_ARADDR),
        .s_axilite_RVALID(s_axilite_RVALID),
        .s_axilite_RREADY(s_axilite_RREADY),
        .s_axilite_RDATA(s_axilite_RDATA),
        .s_axilite_RRESP(s_axilite_RRESP)    );

endmodule // thresholding_axi_wrapper