# Auto-generated by Brainsmith Hardware Kernel Generator
# Generated from: /home/tafk/dev/brainsmith-2/brainsmith/tools/hw_kernel_gen/tests/test_kernel_e2e.sv
# Date: 2025-06-30T15:25:57.563383

from brainsmith.tools.hw_kernel_gen.auto_rtl_backend import AutoRTLBackend
from .test_kernel_e2e_hw_custom_op import TestKernelE2e
from qonnx.core.datatype import DataType


class test_kernel_e2e_rtl(TestKernelE2e, AutoRTLBackend):
    """RTL backend for test_kernel_e2e operation.
    
    Auto-generated from SystemVerilog RTL analysis.
    Uses explicit parameter resolution generated at compile-time.
    """
    
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)
    
    @property
    def finn_rtllib_module(self) -> str:
        """Return finn-rtllib module name for this operation."""
        return ""
    
    def get_nodeattr_types(self):
        """Define all node attributes including RTL-specific parameters."""
        # Get interface datatype attributes from HWCustomOp parent
        my_attrs = super().get_nodeattr_types()
        
        # Add RTL-specific algorithm parameters
        rtl_attrs = {
            "accumulatorDataType": ('s', False, 'INT8'),
            "thresholdDataType": ('s', False, 'INT8'),
            "PE": ('i', True, None),
            "ACTIVATION_TYPE": ('i', True, None),
        }
        my_attrs.update(rtl_attrs)
        
        return my_attrs
    
    def prepare_codegen_rtl_values(self, model):
        """Explicit parameter resolution for RTL template generation."""
        code_gen_dict = {}
        
        # Basic module information
        code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"] = [self.get_verilog_top_module_name()]
        code_gen_dict["$TOP_MODULE$"] = code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"]
        
        # Standard stream width variables
        code_gen_dict["$IBITS$"] = [str(self.get_instream_width())]
        code_gen_dict["$OBITS$"] = [str(self.get_outstream_width())]
        
        # Explicit parameter assignments (generated from CodegenBinding at compile-time)
        code_gen_dict["$INPUT_BDIM$"] = [str(self._get_interface_bdim("s_axis_input", 0))]  # Block dimension from KernelModel for s_axis_input
        code_gen_dict["$INPUT_SDIM$"] = [str(self._get_interface_sdim("s_axis_input", 0))]  # Stream dimension from KernelModel for s_axis_input
        code_gen_dict["$WEIGHT_BDIM$"] = [str(self._get_interface_bdim("s_axis_weights", 0))]  # Block dimension from KernelModel for s_axis_weights
        code_gen_dict["$WEIGHT_SDIM$"] = [str(self._get_interface_sdim("s_axis_weights", 0))]  # Stream dimension from KernelModel for s_axis_weights
        code_gen_dict["$OUTPUT_BDIM$"] = [str(self._get_interface_bdim("m_axis_output", 0))]  # Block dimension from KernelModel for m_axis_output
        code_gen_dict["$PE$"] = [str(self.get_nodeattr("PE"))]  # Algorithm parameter PE
        code_gen_dict["$ACTIVATION_TYPE$"] = [str(self.get_nodeattr("ACTIVATION_TYPE"))]  # Algorithm parameter ACTIVATION_TYPE
        code_gen_dict["$MEM_DEPTH$"] = [str(self.calc_memory_depth())]  # Derived parameter MEM_DEPTH
        code_gen_dict["$INPUT_WIDTH$"] = [str(self._get_interface_width("s_axis_input"))]  # Interface s_axis_input width from KernelModel
        code_gen_dict["$WEIGHT_WIDTH$"] = [str(self._get_interface_width("s_axis_weights"))]  # Interface s_axis_weights width from KernelModel
        code_gen_dict["$WEIGHT_SIGNED$"] = [str(1 if self._get_interface_signed("s_axis_weights") else 0)]  # Interface s_axis_weights signed from KernelModel
        code_gen_dict["$OUTPUT_WIDTH$"] = [str(self._get_interface_width("m_axis_output"))]  # Interface m_axis_output width from KernelModel
        code_gen_dict["$ACC_WIDTH$"] = [str(DataType[self.get_nodeattr("accumulatorDataType")].bitwidth())]  # Internal accumulator width parameter
        code_gen_dict["$ACC_SIGNED$"] = [str(1 if DataType[self.get_nodeattr("accumulatorDataType")].signed() else 0)]  # Internal accumulator signed parameter
        code_gen_dict["$THRESH_WIDTH$"] = [str(DataType[self.get_nodeattr("thresholdDataType")].bitwidth())]  # Internal threshold width parameter
        
        return code_gen_dict
    
    def get_supporting_rtl_files(self) -> list:
        """Get list of supporting RTL files to include."""
        return [
        ]