# Auto-generated by Brainsmith Hardware Kernel Generator
# Generated from: /home/tafk/dev/brainsmith-2/brainsmith/tools/hw_kernel_gen/tests/test_kernel_e2e.sv
# Date: 2025-06-30T07:36:27.587563

from brainsmith.dataflow.core.auto_rtl_backend import AutoRTLBackend
from qonnx.core.datatype import DataType


class test_kernel_e2e_rtl(AutoRTLBackend):
    """RTL backend for test_kernel_e2e operation.
    
    Auto-generated from SystemVerilog RTL analysis.
    Uses explicit parameter resolution generated at compile-time.
    """
    
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)
    
    @property
    def finn_rtllib_module(self) -> str:
        """Return finn-rtllib module name for this operation."""
        return ""
    
    def get_nodeattr_types(self):
        """Explicit node attribute types for RTL backend."""
        my_attrs = {
            "INPUT_BDIM": ('i', True, None),
            "INPUT_SDIM": ('i', True, None),
            "WEIGHT_BDIM": ('i', True, None),
            "WEIGHT_SDIM": ('i', True, None),
            "OUTPUT_BDIM": ('i', True, None),
            "PE": ('i', True, None),
            "ACTIVATION_TYPE": ('i', True, None),
            "s_axis_inputDataType": ('s', False, 'INT8'),
            "s_axis_weightsDataType": ('s', False, 'INT8'),
            "m_axis_outputDataType": ('s', False, 'INT8'),
        }
        
        # Merge with parent class attributes
        my_attrs.update(AutoRTLBackend.get_nodeattr_types(self))
        
        return my_attrs
    
    def prepare_codegen_rtl_values(self, model):
        """Explicit parameter resolution for RTL template generation."""
        code_gen_dict = {}
        
        # Basic module information
        code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"] = [self.get_verilog_top_module_name()]
        code_gen_dict["$TOP_MODULE$"] = code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"]
        
        # Standard stream width variables
        code_gen_dict["$IBITS$"] = [str(self.get_instream_width())]
        code_gen_dict["$OBITS$"] = [str(self.get_outstream_width())]
        
        # Explicit parameter assignments (generated from CodegenBinding at compile-time)
        code_gen_dict["$INPUT_BDIM$"] = [str(self.get_nodeattr("INPUT_BDIM"))]  # Algorithm parameter INPUT_BDIM
        code_gen_dict["$INPUT_SDIM$"] = [str(self.get_nodeattr("INPUT_SDIM"))]  # Algorithm parameter INPUT_SDIM
        code_gen_dict["$WEIGHT_BDIM$"] = [str(self.get_nodeattr("WEIGHT_BDIM"))]  # Algorithm parameter WEIGHT_BDIM
        code_gen_dict["$WEIGHT_SDIM$"] = [str(self.get_nodeattr("WEIGHT_SDIM"))]  # Algorithm parameter WEIGHT_SDIM
        code_gen_dict["$OUTPUT_BDIM$"] = [str(self.get_nodeattr("OUTPUT_BDIM"))]  # Algorithm parameter OUTPUT_BDIM
        code_gen_dict["$PE$"] = [str(self.get_nodeattr("PE"))]  # Algorithm parameter PE
        code_gen_dict["$ACTIVATION_TYPE$"] = [str(self.get_nodeattr("ACTIVATION_TYPE"))]  # Algorithm parameter ACTIVATION_TYPE
        code_gen_dict["$MEM_DEPTH$"] = [str(self.calc_memory_depth())]  # Derived parameter MEM_DEPTH
        code_gen_dict["$INPUT_WIDTH$"] = [str(DataType[self.get_nodeattr("s_axis_inputDataType")].bitwidth())]  # Interface s_axis_input width parameter
        code_gen_dict["$WEIGHT_WIDTH$"] = [str(DataType[self.get_nodeattr("s_axis_weightsDataType")].bitwidth())]  # Interface s_axis_weights width parameter
        code_gen_dict["$WEIGHT_SIGNED$"] = [str(1 if DataType[self.get_nodeattr("s_axis_weightsDataType")].signed() else 0)]  # Interface s_axis_weights signed parameter
        code_gen_dict["$OUTPUT_WIDTH$"] = [str(DataType[self.get_nodeattr("m_axis_outputDataType")].bitwidth())]  # Interface m_axis_output width parameter
        code_gen_dict["$ACC_WIDTH$"] = [str(DataType[self.get_nodeattr("accumulatorDataType")].bitwidth())]  # Internal accumulator width parameter
        code_gen_dict["$ACC_SIGNED$"] = [str(1 if DataType[self.get_nodeattr("accumulatorDataType")].signed() else 0)]  # Internal accumulator signed parameter
        code_gen_dict["$THRESH_WIDTH$"] = [str(DataType[self.get_nodeattr("thresholdDataType")].bitwidth())]  # Internal threshold width parameter
        
        return code_gen_dict
    
    def get_supporting_rtl_files(self) -> list:
        """Get list of supporting RTL files to include."""
        return [
        ]