// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: /home/tafk/dev/brainsmith-2/brainsmith/tools/hw_kernel_gen/tests/test_kernel_e2e.sv
// Date: 2025-06-20T06:42:13.761939

module test_kernel_e2e_wrapper #(
    // Parameters from original module
    parameter PE = $PE$,
    parameter SIMD = $SIMD$,
    parameter INPUT_WIDTH = $INPUT_WIDTH$,
    parameter WEIGHT_WIDTH = $WEIGHT_WIDTH$,
    parameter WEIGHT_SIGNED = $WEIGHT_SIGNED$,
    parameter OUTPUT_WIDTH = $OUTPUT_WIDTH$,
    parameter ACC_WIDTH = $ACC_WIDTH$,
    parameter ACC_SIGNED = $ACC_SIGNED$,
    parameter THRESH_WIDTH = $THRESH_WIDTH$,
    parameter INPUT_BDIM = $INPUT_BDIM$,
    parameter INPUT_SDIM = $INPUT_SDIM$,
    parameter WEIGHT_BDIM = $WEIGHT_BDIM$,
    parameter MEM_DEPTH = $MEM_DEPTH$,
    parameter ACTIVATION_TYPE = $ACTIVATION_TYPE$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // s_axis_input: INPUT interface
    input wire [$S_AXIS_INPUT_STREAM_WIDTH$-1:0] s_axis_input_TDATA,
    input wire s_axis_input_TVALID,
    output wire s_axis_input_TREADY,
    // m_axis_output: OUTPUT interface
    output wire [$M_AXIS_OUTPUT_STREAM_WIDTH$-1:0] m_axis_output_TDATA,
    output wire m_axis_output_TVALID,
    input wire m_axis_output_TREADY,
    // s_axis_weights: WEIGHT interface
    input wire [$S_AXIS_WEIGHTS_STREAM_WIDTH$-1:0] s_axis_weights_TDATA,
    input wire s_axis_weights_TVALID,
    output wire s_axis_weights_TREADY,
    // s_axilite_config: CONFIG interface (AXI-Lite)
    input wire s_axilite_config_AWVALID,
    output wire s_axilite_config_AWREADY,
    input wire [31:0] s_axilite_config_AWADDR,
    input wire s_axilite_config_WVALID,
    output wire s_axilite_config_WREADY,
    input wire [31:0] s_axilite_config_WDATA,
    input wire [3:0] s_axilite_config_WSTRB,
    output wire s_axilite_config_BVALID,
    input wire s_axilite_config_BREADY,
    output wire [1:0] s_axilite_config_BRESP,
    input wire s_axilite_config_ARVALID,
    output wire s_axilite_config_ARREADY,
    input wire [31:0] s_axilite_config_ARADDR,
    output wire s_axilite_config_RVALID,
    input wire s_axilite_config_RREADY,
    output wire [31:0] s_axilite_config_RDATA,
    output wire [1:0] s_axilite_config_RRESP);

    // Instantiate the wrapped kernel
    test_kernel_e2e #(
        // Pass parameters
        .PE(PE),
        .SIMD(SIMD),
        .INPUT_WIDTH(INPUT_WIDTH),
        .WEIGHT_WIDTH(WEIGHT_WIDTH),
        .WEIGHT_SIGNED(WEIGHT_SIGNED),
        .OUTPUT_WIDTH(OUTPUT_WIDTH),
        .ACC_WIDTH(ACC_WIDTH),
        .ACC_SIGNED(ACC_SIGNED),
        .THRESH_WIDTH(THRESH_WIDTH),
        .INPUT_BDIM(INPUT_BDIM),
        .INPUT_SDIM(INPUT_SDIM),
        .WEIGHT_BDIM(WEIGHT_BDIM),
        .MEM_DEPTH(MEM_DEPTH),
        .ACTIVATION_TYPE(ACTIVATION_TYPE)    ) test_kernel_e2e_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // s_axis_input connections
        .s_axis_input_TDATA(s_axis_input_TDATA),
        .s_axis_input_TVALID(s_axis_input_TVALID),
        .s_axis_input_TREADY(s_axis_input_TREADY),
        // m_axis_output connections
        .m_axis_output_TDATA(m_axis_output_TDATA),
        .m_axis_output_TVALID(m_axis_output_TVALID),
        .m_axis_output_TREADY(m_axis_output_TREADY),
        // s_axis_weights connections
        .s_axis_weights_TDATA(s_axis_weights_TDATA),
        .s_axis_weights_TVALID(s_axis_weights_TVALID),
        .s_axis_weights_TREADY(s_axis_weights_TREADY),
        // s_axilite_config connections
        .s_axilite_config_AWVALID(s_axilite_config_AWVALID),
        .s_axilite_config_AWREADY(s_axilite_config_AWREADY),
        .s_axilite_config_AWADDR(s_axilite_config_AWADDR),
        .s_axilite_config_WVALID(s_axilite_config_WVALID),
        .s_axilite_config_WREADY(s_axilite_config_WREADY),
        .s_axilite_config_WDATA(s_axilite_config_WDATA),
        .s_axilite_config_WSTRB(s_axilite_config_WSTRB),
        .s_axilite_config_BVALID(s_axilite_config_BVALID),
        .s_axilite_config_BREADY(s_axilite_config_BREADY),
        .s_axilite_config_BRESP(s_axilite_config_BRESP),
        .s_axilite_config_ARVALID(s_axilite_config_ARVALID),
        .s_axilite_config_ARREADY(s_axilite_config_ARREADY),
        .s_axilite_config_ARADDR(s_axilite_config_ARADDR),
        .s_axilite_config_RVALID(s_axilite_config_RVALID),
        .s_axilite_config_RREADY(s_axilite_config_RREADY),
        .s_axilite_config_RDATA(s_axilite_config_RDATA),
        .s_axilite_config_RRESP(s_axilite_config_RRESP)    );

endmodule // test_kernel_e2e_wrapper