# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: "Baseline FINN"
description: "Core FINN build steps (no kernels)"

# Minimal configuration for estimates only
clock_ns: 5.0                       # Target clock period in nanoseconds

design_space:
  kernels: []
  steps:
    - "cleanup"  # custom_step_cleanup
    - "qonnx_to_finn"
    # REQUIRED: Layout normalization must run before kernel inference
    # All Brainsmith kernels assume NHWC (channel-last) layout for dataflow.
    # This step converts any NCHW tensors to NHWC globally, eliminating the
    # need for per-kernel layout checking and ensuring uniform dataflow behavior.
    - "normalize_dataflow_layouts"
    - "infer_kernels" # Brainsmith dynamic kernel inference (assumes NHWC)
    - "create_dataflow_partition"
    - "specialize_layers"
    - "target_fps_parallelization"
    - "apply_folding_config"
    - "minimize_bit_width"
    - "generate_estimate_reports"
    - "hw_codegen"
    - "hw_ipgen"
    - "set_fifo_depths"
    - "create_stitched_ip"
    - "measure_rtlsim_performance"

