name: 'Collect Artifacts'
description: 'Collect CI artifacts safely'
inputs:
  artifact-directory:
    description: 'Directory to store artifacts'
    type: string
    default: 'artifacts'

runs:
  using: 'composite'
  steps:
    - name: Validate artifact directory
      shell: bash
      run: |
        ARTIFACT_DIR="${{ inputs.artifact-directory }}"
        
        # Validate directory name
        if [[ ! "$ARTIFACT_DIR" =~ ^[a-zA-Z0-9_\-]+$ ]]; then
            echo "ERROR: Artifact directory contains invalid characters"
            echo "Allowed: alphanumeric, underscore, hyphen"
            exit 1
        fi
        
        # Prevent path traversal
        if [[ "$ARTIFACT_DIR" =~ \.\./|^/ ]]; then
            echo "ERROR: Invalid artifact directory path (path traversal detected)"
            exit 1
        fi
        
        echo "✓ Artifact directory validated: $ARTIFACT_DIR"
    
    - name: Collect artifacts
      shell: bash
      run: |
        ARTIFACT_DIR="${{ inputs.artifact-directory }}"
        mkdir -p "$ARTIFACT_DIR"
        
        echo "=== Collecting system info ==="
        df -h > "$ARTIFACT_DIR/disk_usage.txt" 2>/dev/null || true
        free -h > "$ARTIFACT_DIR/memory_usage.txt" 2>/dev/null || true
        
        echo "=== Collecting container info ==="
        if [ -x ./ctl-docker.sh ]; then
            ./ctl-docker.sh status > "$ARTIFACT_DIR/container_status.txt" 2>&1 || echo "Status failed" > "$ARTIFACT_DIR/container_status.txt"
            ./ctl-docker.sh logs > "$ARTIFACT_DIR/container.log" 2>&1 || echo "No logs" > "$ARTIFACT_DIR/container.log"
        fi

        echo "=== Collecting container diagnostics ==="
        # Collect diagnostics extracted by docker-exec action (if COLLECT_DIAGNOSTICS=1 was enabled)
        if [ -d diagnostics-from-container ]; then
          echo "Including diagnostics extracted from container"
          mkdir -p "$ARTIFACT_DIR/finn-xsi-diagnostics"
          cp -r diagnostics-from-container/* "$ARTIFACT_DIR/finn-xsi-diagnostics/" 2>&1 || true
          echo "✓ Container diagnostics included"
          ls -la "$ARTIFACT_DIR/finn-xsi-diagnostics/" || true
        else
          echo "No container diagnostics found (expected if test succeeded or COLLECT_DIAGNOSTICS not enabled)"
        fi

        echo "✓ Artifacts collected in $ARTIFACT_DIR"