name: 'Build Smithy Image'
description: 'Build and verify Smithy Docker image'

runs:
  using: 'composite'
  steps:
    - name: Build and verify Docker image
      shell: bash
      run: |
        chmod +x smithy
        echo "=== Building Docker image ==="
        ./smithy build
        
        echo "=== Verifying image was built ==="
        if docker images | grep -q "microsoft/brainsmith"; then
            echo "✓ Docker image built and verified successfully"
        else
            echo "ERROR: Docker image not found after build"
            exit 1
        fi