# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""CLI-specific constants.

This module centralizes CLI-specific constants:
- Runtime environment variable names (not managed by Pydantic)
- CLI entry point names
- Exit codes

Note: Configuration file paths are in brainsmith.settings.constants.
Most environment variables (BSMITH_*) are auto-generated by Pydantic's
SystemConfig with env_prefix='BSMITH_'. Only runtime flags like ENV_QUIET
are defined here.
"""

from enum import IntEnum

# ============================================================================
# Environment Variables
# ============================================================================

# Runtime flags (not managed by Pydantic SystemConfig)
ENV_QUIET = "BSMITH_QUIET"

# ============================================================================
# CLI Names
# ============================================================================

CLI_NAME_BRAINSMITH = "brainsmith"
CLI_NAME_SMITH = "smith"

# ============================================================================
# Exit Codes (BSD sysexits.h standard)
# ============================================================================


class ExitCode(IntEnum):
    """BSD sysexits.h standard exit codes for shell compatibility.

    See: https://man.freebsd.org/cgi/man.cgi?query=sysexits
    """

    OK = 0  # Successful termination
    USAGE = 64  # Command line usage error
    DATAERR = 65  # Data format error (validation)
    SOFTWARE = 70  # Internal software error
    CONFIG = 78  # Configuration error
    INTERRUPTED = 130  # SIGINT (128 + 2)
