name: 'Docker GHCR Login'
description: 'Login to GitHub Container Registry'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    type: string
    required: true
  github-actor:
    description: 'GitHub actor username'
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to GHCR
      shell: bash
      run: |
        echo "Attempting GHCR login..."
        if ! echo "${{ inputs.github-token }}" | docker login ghcr.io -u "${{ inputs.github-actor }}" --password-stdin 2>/dev/null; then
            echo "ERROR: Failed to authenticate with GitHub Container Registry"
            echo "Please check GITHUB_TOKEN permissions and network connectivity"
            exit 1
        fi
        echo "✓ GHCR login successful"