// Auto-generated by Brainsmith Kernel Integrator for rope_axi
// Generated from: /home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv

module rope_axi_wrapper #(
    // General algorithm parameters
    parameter HEAD_DIM = $HEAD_DIM$,
    parameter SINCOS_WIDTH = $SINCOS_WIDTH$,
    parameter COS_INIT_FILE = $COS_INIT_FILE$,
    parameter SIN_INIT_FILE = $SIN_INIT_FILE$,
    // s_axis interface parameters
    parameter SEQ_LEN = $SEQ_LEN$,
    parameter HIDDEN_DIM = $HIDDEN_DIM$,
    parameter SIMD = $SIMD$,
    parameter ELEM_BITS = $ELEM_BITS$,) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    // input: INPUT interface (RTL: s_axis)
    input wire [$S_AXIS_STREAM_WIDTH$-1:0] input_TDATA,
    input wire input_TVALID,
    output wire input_TREADY,
    // output: OUTPUT interface (RTL: m_axis)
    output wire [$M_AXIS_STREAM_WIDTH$-1:0] output_TDATA,
    output wire output_TVALID,
    input wire output_TREADY,);

    // Instantiate the wrapped kernel
    rope_axi #(
        // General algorithm parameters
        .HEAD_DIM(HEAD_DIM),
        .SINCOS_WIDTH(SINCOS_WIDTH),
        .COS_INIT_FILE(COS_INIT_FILE),
        .SIN_INIT_FILE(SIN_INIT_FILE),
        // s_axis interface parameters
        .SEQ_LEN(SEQ_LEN),
        .HIDDEN_DIM(HIDDEN_DIM),
        .SIMD(SIMD),
        .ELEM_BITS(ELEM_BITS),    ) rope_axi_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        // s_axis connections (from input)
        .s_axis_tdata(input_TDATA),
        .s_axis_tvalid(input_TVALID),
        .s_axis_tready(input_TREADY),
        // m_axis connections (to output)  
        .m_axis_tdata(output_TDATA),
        .m_axis_tvalid(output_TVALID),
        .m_axis_tready(output_TREADY)    );

endmodule // rope_axi_wrapper