# Auto-generated by Brainsmith Kernel Integrator for rope_axi
# Generated from: /home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv

from typing import List, Dict, Tuple, Any
import os
import shutil
from pathlib import Path

from brainsmith.core.finn.auto_rtl_backend import AutoRTLBackend
from .rope_axi import RopeAxi
from qonnx.core.datatype import DataType


class RopeAxi_rtl(RopeAxi, AutoRTLBackend):
    """
    RTL backend for rope_axi operation.
    
    Auto-generated from SystemVerilog RTL: /home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv
    Uses direct parameter resolution from KernelMetadata structure.
    """
    
    def __init__(self, onnx_node, **kwargs):
        """Initialize rope_axi_rtl backend."""
        super().__init__(onnx_node, **kwargs)
    
    def get_nodeattr_types(self):
        """
        Define all node attributes including RTL-specific parameters.
        
        Inherits interface attributes from HWCustomOp parent and adds
        RTL-specific algorithm parameters.
        """
        # Get interface datatype attributes from HWCustomOp parent
        my_attrs = super().get_nodeattr_types()
        
        # Add RTL-specific algorithm parameters
        rtl_attrs = {
            "HEAD_DIM": ('i', True, None),
            "SINCOS_WIDTH": ('i', True, None),
            "COS_INIT_FILE": ('s', True, ""),
            "SIN_INIT_FILE": ('s', True, ""),
            # AXI-Lite enable parameter
            "USE_AXILITE": ('i', True, 0),  # No AXI-Lite interface
        }
        my_attrs.update(rtl_attrs)
        
        # Add HDL generation attributes
        my_attrs.update({
            "gen_top_module": ("s", False, ""),
            "ipgen_path": ("s", False, ""),
            "ip_path": ("s", False, ""),
        })
        
        return my_attrs
    
    def prepare_codegen_rtl_values(self, model):
        """
        Prepare parameter values for RTL code generation.
        
        Maps node attributes and interface properties to RTL template variables.
        Uses direct access to generate clear, traceable mappings.
        """
        code_gen_dict = {}
        
        # Basic module information
        code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"] = [self.get_verilog_top_module_name()]
        code_gen_dict["$TOP_MODULE$"] = code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"]
        
        # Standard stream width variables
        code_gen_dict["$IBITS$"] = [str(self.get_instream_width())]
        code_gen_dict["$OBITS$"] = [str(self.get_outstream_width())]
        
        # Direct parameter assignments from KernelMetadata
        code_gen_dict["$HEAD_DIM$"] = [str(self.get_nodeattr("HEAD_DIM"))]
        code_gen_dict["$SINCOS_WIDTH$"] = [str(self.get_nodeattr("SINCOS_WIDTH"))]
        code_gen_dict["$COS_INIT_FILE$"] = [str(self.get_nodeattr("COS_INIT_FILE"))]
        code_gen_dict["$SIN_INIT_FILE$"] = [str(self.get_nodeattr("SIN_INIT_FILE"))]
        
        # Interface-specific parameters
        # s_axis BDIM parameters
        code_gen_dict["$SEQ_LEN$"] = [str(self._get_interface_bdim("input", 0))]
        code_gen_dict["$HIDDEN_DIM$"] = [str(self._get_interface_bdim("input", 1))]
        # s_axis SDIM parameters  
        code_gen_dict["$SIMD$"] = [str(self._get_interface_sdim("input", 0))]
        
        # Interface datatype widths
        code_gen_dict["$S_AXIS_WIDTH$"] = [str(self._get_interface_width("input"))]
        code_gen_dict["$M_AXIS_WIDTH$"] = [str(self._get_interface_width("output"))]
        
        # Config interface parameters
        
        # Standard interface width mappings
        code_gen_dict["$S_AXIS_STREAM_WIDTH$"] = [str(self._get_interface_width("input"))]
        code_gen_dict["$M_AXIS_STREAM_WIDTH$"] = [str(self._get_interface_width("output"))]
        
        # AXI-Lite configuration enable
        code_gen_dict["$USE_AXILITE$"] = [str(0)]
        
        # Extract PE and CHANNELS parameters if they exist
        # These often appear in shape expressions but need to be available as parameters
        if hasattr(self, 'get_nodeattr'):
            try:
                pe_val = self.get_nodeattr("PE")
                code_gen_dict["$PE$"] = [str(pe_val)]
            except Exception:
                pass
            try:
                channels_val = self.get_nodeattr("CHANNELS")
                code_gen_dict["$CHANNELS$"] = [str(channels_val)]
            except Exception:
                pass
        
        return code_gen_dict
    
    def get_included_rtl_filenames(self) -> List[str]:
        """Get list of included RTL file names (basename only)."""
        return [
            os.path.basename("/home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv"),
            os.path.basename("rope.sv"),
        ]
    
    def generate_hdl(self, model, fpgapart, clk):
        """Generate HDL from pre-generated wrapper template."""
        # Get code generation directory
        code_gen_dir = self.get_nodeattr("code_gen_dir_ipgen")
        os.makedirs(code_gen_dir, exist_ok=True)
        
        # Save top module name
        topname = self.get_verilog_top_module_name()
        self.set_nodeattr("gen_top_module", topname)
        
        # Get template variables
        code_gen_dict = self.prepare_codegen_rtl_values(model)
        
        # Find the pre-generated wrapper template
        module_dir = Path(__file__).parent
        wrapper_name = "rope_axi_wrapper.v"
        wrapper_path = module_dir / wrapper_name
        
        if wrapper_path.exists():
            # Read wrapper template
            with open(wrapper_path, "r") as f:
                template_content = f.read()
            
            # Apply template substitution
            for placeholder, values in code_gen_dict.items():
                value = values[0] if isinstance(values, list) and values else str(values)
                template_content = template_content.replace(placeholder, value)
            
            # Write processed wrapper
            output_path = os.path.join(code_gen_dir, f"{topname}.v")
            with open(output_path, "w") as f:
                f.write(template_content)
        else:
            raise FileNotFoundError(
                f"Wrapper template not found at {wrapper_path}. "
                "Ensure the wrapper file is in the same directory as this RTL backend."
            )
        
        # Copy all included RTL files from kernel metadata
        included_files = ['/home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv', 'rope.sv']
        self.copy_included_rtl_files(included_files, code_gen_dir)
        
        # Set paths for downstream tools
        self.set_nodeattr("ipgen_path", code_gen_dir)
        self.set_nodeattr("ip_path", code_gen_dir)
    
    
    def get_verilog_top_module_intf_names(self):
        """Return interface names for Verilog module based on actual RTL signal names."""
        intf_names = {}
        
        # Clock and reset signals from control interface
        intf_names["clk"] = ["ap_clk"]
        intf_names["rst"] = ["ap_rst_n"]
        
        # Stream interface names based on kernel metadata
        # Input stream interfaces (excluding weights)
        intf_names["s_axis"] = [
            ("in0_V", self.get_instream_width_padded(0)),
        ]
        
        # Output stream interfaces
        intf_names["m_axis"] = [
            ("out0_V", self.get_outstream_width_padded(0)),
        ]
        
        
        return intf_names
    
    ############################################################################
    # ======================= MANUALLY IMPLEMENT FUNCTIONS BELOW ===============
    # Add any custom methods specific to your RTL backend here
    ############################################################################


# Kernel metadata reference
"""
rope_axi RTL Backend Specification:

Module: rope_axi
Source: /home/tafk/dev/brainsmith-3/brainsmith/kernels/rotaryembedding/hdl/rope_axi.sv

Parameters:
- HEAD_DIM: RTL parameter (nodeattr: HEAD_DIM)
- SINCOS_WIDTH: RTL parameter (nodeattr: SINCOS_WIDTH)
- COS_INIT_FILE: RTL parameter (nodeattr: COS_INIT_FILE)
- SIN_INIT_FILE: RTL parameter (nodeattr: SIN_INIT_FILE)

Interfaces:
- s_axis: INPUT interface- m_axis: OUTPUT interface

Template Variables Generated:
- Module and stream width variables
- $HEAD_DIM$: from nodeattr 'HEAD_DIM'
- $SINCOS_WIDTH$: from nodeattr 'SINCOS_WIDTH'
- $COS_INIT_FILE$: from nodeattr 'COS_INIT_FILE'
- $SIN_INIT_FILE$: from nodeattr 'SIN_INIT_FILE'
- $S_AXIS_WIDTH$: interface datatype width
- $SEQ_LEN$: s_axis BDIM parameter
- $HIDDEN_DIM$: s_axis BDIM parameter
- $SIMD$: s_axis SDIM parameter
- $M_AXIS_WIDTH$: interface datatype width
"""