# Auto-generated by Brainsmith Hardware Kernel Generator
# Generated from: brainsmith/tools/hw_kernel_gen/tests/test_axilite_pragma.sv
# Date: 2025-06-20T22:24:53.821315

from brainsmith.dataflow.core.auto_rtl_backend import AutoRTLBackend


class test_axilite_rtl(AutoRTLBackend):
    """RTL backend for test_axilite operation.
    
    Auto-generated from SystemVerilog RTL analysis.
    
    Hardware accelerator operation: test_axilite
    """
    
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)
    
    @property
    def finn_rtllib_module(self) -> str:
        """Return finn-rtllib module name for this operation."""
        return "test_axilite"
    
    def get_nodeattr_types(self):
        """Get node attribute types for RTLBackend (algorithm parameters only)."""
        my_attrs = {}
        
        # Only expose algorithm parameters (exposed parameters only)
        # Algorithm parameter - optional with default
        my_attrs["MY_CUSTOM_CONFIG"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["USE_AXILITE"] = ("i", False, 1)
        # Algorithm parameter - optional with default
        my_attrs["SOME_OTHER_PARAM"] = ("i", False, 1)
        
        # Standardized AXI-Lite configuration support
        my_attrs["MY_CUSTOM_CONFIG"] = ("i", False, 1, {0, 1})
        
        # Merge with parent class attributes
        my_attrs.update(AutoRTLBackend.get_nodeattr_types(self))
        
        return my_attrs
    
    def prepare_codegen_rtl_values(self, model):
        """Prepare template variables for RTL code generation.
        
        All dictionary values produced in this function are to replace
        their key value(s) in the RTL template files following FINN's pattern.
        """
        code_gen_dict = {}
        
        # Basic module information
        code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"] = [self.get_verilog_top_module_name()]
        code_gen_dict["$TOP_MODULE$"] = code_gen_dict["$MODULE_NAME_AXI_WRAPPER$"]
        
        # Standard stream width variables
        code_gen_dict["$IBITS$"] = [str(self.get_instream_width())]
        code_gen_dict["$OBITS$"] = [str(self.get_outstream_width())]
        
        # Algorithm parameters from node attributes
        code_gen_dict["$MY_CUSTOM_CONFIG$"] = [str(self.get_nodeattr("MY_CUSTOM_CONFIG"))]
        code_gen_dict["$USE_AXILITE$"] = [str(self.get_nodeattr("USE_AXILITE"))]
        code_gen_dict["$SOME_OTHER_PARAM$"] = [str(self.get_nodeattr("SOME_OTHER_PARAM"))]
        
        # BDIM/SDIM parameter linkage (from interface metadata)
        interface_metadata = self.get_interface_metadata()
        for interface in interface_metadata:
            # BDIM parameter linkage
            if hasattr(interface, 'bdim_param') and interface.bdim_param:
                bdim_value = self.get_nodeattr(interface.bdim_param) if interface.bdim_param in ['MY_CUSTOM_CONFIG', 'USE_AXILITE', 'SOME_OTHER_PARAM'] else None
                if bdim_value is not None:
                    code_gen_dict[f"${interface.bdim_param.upper()}$"] = [str(bdim_value)]
            
            # SDIM parameter linkage  
            if hasattr(interface, 'sdim_param') and interface.sdim_param:
                sdim_value = self.get_nodeattr(interface.sdim_param) if interface.sdim_param in ['MY_CUSTOM_CONFIG', 'USE_AXILITE', 'SOME_OTHER_PARAM'] else None
                if sdim_value is not None:
                    code_gen_dict[f"${interface.sdim_param.upper()}$"] = [str(sdim_value)]
        
        # Datatype parameter assignments (generated at template time)
        from qonnx.core.datatype import DataType
        # Internal INPUT width parameter
        code_gen_dict["$INPUT_WIDTH$"] = [str(DataType[self.get_nodeattr("INPUTDataType")].bitwidth())]
        # Internal OUTPUT width parameter
        code_gen_dict["$OUTPUT_WIDTH$"] = [str(DataType[self.get_nodeattr("OUTPUTDataType")].bitwidth())]
        
        # Stream width parameters from DataflowModel
        dataflow_model = self.get_dataflow_model()
        if dataflow_model:
            for iface_name, iface in dataflow_model.interfaces.items():
                # Calculate stream width for this interface
                stream_width = iface.calculate_stream_width()
                # Generate template variable using original interface name (uppercase)
                template_var = f"${iface.name.upper()}_STREAM_WIDTH$"
                code_gen_dict[template_var] = [str(stream_width)]
        
        return code_gen_dict
    
    def get_supporting_rtl_files(self) -> list:
        """Get list of supporting RTL files to include."""
        return [
            "test_axilite_axi.sv",
            "test_axilite.sv",
        ]
    
    def lut_estimation(self) -> int:
        """Estimate LUT usage for test_axilite."""
        # TODO: Implement operation-specific LUT estimation
        # For now, use base class conservative estimate
        return super().lut_estimation()
    
    def bram_estimation(self) -> int:
        """Estimate BRAM usage for test_axilite."""
        # TODO: Implement operation-specific BRAM estimation
        # For now, use base class estimate
        return super().bram_estimation()
    
    def dsp_estimation(self, fpgapart) -> int:
        """Estimate DSP usage for test_axilite."""
        # TODO: Implement operation-specific DSP estimation
        # For now, use base class estimate
        return super().dsp_estimation(fpgapart)
    
