// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: brainsmith/tools/hw_kernel_gen/tests/test_axilite_pragma.sv
// Date: 2025-06-20T22:24:53.835302

module test_axilite_wrapper #(    // General algorithm parameters
    parameter USE_AXILITE = $USE_AXILITE$,
    parameter SOME_OTHER_PARAM = $SOME_OTHER_PARAM$,
    // AXI-Lite configuration parameters
    parameter MY_CUSTOM_CONFIG = $MY_CUSTOM_CONFIG$,
    // INPUT datatype
    parameter INPUT_WIDTH = $INPUT_WIDTH$,
    // OUTPUT datatype
    parameter OUTPUT_WIDTH = $OUTPUT_WIDTH$,
    // s_axis_input interface parameters
    // m_axis_output interface parameters
) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // s_axis_input: INPUT interface
    input wire [$S_AXIS_INPUT_STREAM_WIDTH$-1:0] s_axis_input_TDATA,
    input wire s_axis_input_TVALID,
    output wire s_axis_input_TREADY,
    // m_axis_output: OUTPUT interface
    output wire [$M_AXIS_OUTPUT_STREAM_WIDTH$-1:0] m_axis_output_TDATA,
    output wire m_axis_output_TVALID,
    input wire m_axis_output_TREADY);

    // Instantiate the wrapped kernel
    test_axilite #(        // General algorithm parameters
        .USE_AXILITE(USE_AXILITE),
        .SOME_OTHER_PARAM(SOME_OTHER_PARAM),
        // AXI-Lite configuration parameters
        .MY_CUSTOM_CONFIG(MY_CUSTOM_CONFIG),
        // INPUT datatype
        .INPUT_WIDTH(INPUT_WIDTH),
        // OUTPUT datatype
        .OUTPUT_WIDTH(OUTPUT_WIDTH),
        // s_axis_input interface parameters
        // m_axis_output interface parameters
    ) test_axilite_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // s_axis_input connections
        .s_axis_input_TDATA(s_axis_input_TDATA),
        .s_axis_input_TVALID(s_axis_input_TVALID),
        .s_axis_input_TREADY(s_axis_input_TREADY),
        // m_axis_output connections
        .m_axis_output_TDATA(m_axis_output_TDATA),
        .m_axis_output_TVALID(m_axis_output_TVALID),
        .m_axis_output_TREADY(m_axis_output_TREADY)    );

endmodule // test_axilite_wrapper