// Auto-generated by Brainsmith Hardware Kernel Generator
// Generated from: brainsmith/hw_kernels/thresholding/thresholding_axi_bw.sv
// Date: 2025-07-01T22:30:36.592436

module thresholding_axi_wrapper #(    // General algorithm parameters
    parameter input_FPARG = $INPUT_FPARG$,
    parameter BIAS = $BIAS$,
    parameter THRESHOLDS_PATH = $THRESHOLDS_PATH$,
    parameter DEPTH_TRIGGER_URAM = $DEPTH_TRIGGER_URAM$,
    parameter DEPTH_TRIGGER_BRAM = $DEPTH_TRIGGER_BRAM$,
    parameter DEEP_PIPELINE = $DEEP_PIPELINE$,
    // AXI-Lite configuration parameter
    parameter USE_AXILITE = $USE_AXILITE$,
    // threshold datatype
    parameter T_WIDTH = $T_WIDTH$,
    // input interface parameters
    parameter input_BDIM = $INPUT_BDIM$,
    parameter input_SDIM = $INPUT_SDIM$,
    parameter input_WIDTH = $INPUT_WIDTH$,
    parameter input_SIGNED = $INPUT_SIGNED$,
    // output interface parameters
    parameter output_WIDTH = $OUTPUT_WIDTH$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    input wire ap_start,
    output wire ap_done,
    output wire ap_idle,
    output wire ap_ready,
    // input: INPUT interface
    input wire [$INPUT_STREAM_WIDTH$-1:0] input_TDATA,
    input wire input_TVALID,
    output wire input_TREADY,
    // output: OUTPUT interface
    output wire [$OUTPUT_STREAM_WIDTH$-1:0] output_TDATA,
    output wire output_TVALID,
    input wire output_TREADY,
    // threhsold: CONFIG interface (AXI-Lite)
    input wire threhsold_AWVALID,
    output wire threhsold_AWREADY,
    input wire [31:0] threhsold_AWADDR,
    input wire threhsold_WVALID,
    output wire threhsold_WREADY,
    input wire [31:0] threhsold_WDATA,
    input wire [3:0] threhsold_WSTRB,
    output wire threhsold_BVALID,
    input wire threhsold_BREADY,
    output wire [1:0] threhsold_BRESP,
    input wire threhsold_ARVALID,
    output wire threhsold_ARREADY,
    input wire [31:0] threhsold_ARADDR,
    output wire threhsold_RVALID,
    input wire threhsold_RREADY,
    output wire [31:0] threhsold_RDATA,
    output wire [1:0] threhsold_RRESP);

    // Instantiate the wrapped kernel
    thresholding_axi #(        // General algorithm parameters
        .input_FPARG(input_FPARG),
        .BIAS(BIAS),
        .THRESHOLDS_PATH(THRESHOLDS_PATH),
        .DEPTH_TRIGGER_URAM(DEPTH_TRIGGER_URAM),
        .DEPTH_TRIGGER_BRAM(DEPTH_TRIGGER_BRAM),
        .DEEP_PIPELINE(DEEP_PIPELINE),
        // AXI-Lite configuration parameters
        .USE_AXILITE(USE_AXILITE),
        // threshold datatype
        .T_WIDTH(T_WIDTH),
        // input interface parameters
        .input_BDIM(input_BDIM),
        .input_SDIM(input_SDIM),
        .input_WIDTH(input_WIDTH),
        .input_SIGNED(input_SIGNED),
        // output interface parameters
        .output_WIDTH(output_WIDTH)    ) thresholding_axi_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        .ap_start(ap_start),
        .ap_done(ap_done),
        .ap_idle(ap_idle),
        .ap_ready(ap_ready),
        // input connections
        .input_TDATA(input_TDATA),
        .input_TVALID(input_TVALID),
        .input_TREADY(input_TREADY),
        // output connections
        .output_TDATA(output_TDATA),
        .output_TVALID(output_TVALID),
        .output_TREADY(output_TREADY),
        // threhsold connections
        .threhsold_AWVALID(threhsold_AWVALID),
        .threhsold_AWREADY(threhsold_AWREADY),
        .threhsold_AWADDR(threhsold_AWADDR),
        .threhsold_WVALID(threhsold_WVALID),
        .threhsold_WREADY(threhsold_WREADY),
        .threhsold_WDATA(threhsold_WDATA),
        .threhsold_WSTRB(threhsold_WSTRB),
        .threhsold_BVALID(threhsold_BVALID),
        .threhsold_BREADY(threhsold_BREADY),
        .threhsold_BRESP(threhsold_BRESP),
        .threhsold_ARVALID(threhsold_ARVALID),
        .threhsold_ARREADY(threhsold_ARREADY),
        .threhsold_ARADDR(threhsold_ARADDR),
        .threhsold_RVALID(threhsold_RVALID),
        .threhsold_RREADY(threhsold_RREADY),
        .threhsold_RDATA(threhsold_RDATA),
        .threhsold_RRESP(threhsold_RRESP)    );

endmodule // thresholding_axi_wrapper