// Auto-generated by Brainsmith Kernel Integrator
// Generated from: brainsmith/kernels/thresholding/thresholding_axi_bw.sv

module thresholding_axi_wrapper #(
    // General algorithm parameters
    parameter input_FPARG = $INPUT_FPARG$,
    parameter BIAS = $BIAS$,
    parameter THRESHOLDS_PATH = $THRESHOLDS_PATH$,
    parameter DEPTH_TRIGGER_URAM = $DEPTH_TRIGGER_URAM$,
    parameter DEPTH_TRIGGER_BRAM = $DEPTH_TRIGGER_BRAM$,
    parameter DEEP_PIPELINE = $DEEP_PIPELINE$,
    // AXI-Lite configuration parameter
    parameter USE_AXILITE = $USE_AXILITE$,
    // threshold datatype
    parameter T_WIDTH = $T_WIDTH$,
    // input interface parameters
    parameter input_BDIM = $INPUT_BDIM$,
    parameter input_SDIM = $INPUT_SDIM$,
    parameter input_WIDTH = $INPUT_WIDTH$,
    parameter input_SIGNED = $INPUT_SIGNED$,
    // output interface parameters
    parameter output_WIDTH = $OUTPUT_WIDTH$) (
    // Global Control
    input wire ap_clk,
    input wire ap_rst_n,
    // input: INPUT interface (RTL: input)
    input wire [$INPUT_STREAM_WIDTH$-1:0] input_TDATA,
    input wire input_TVALID,
    output wire input_TREADY,
    // output: OUTPUT interface (RTL: output)
    output wire [$OUTPUT_STREAM_WIDTH$-1:0] output_TDATA,
    output wire output_TVALID,
    input wire output_TREADY,
    // weight: CONFIG interface (AXI-Lite, RTL: threshold)
    // Write Address Channel
    input wire weight_AWVALID,
    output wire weight_AWREADY,
    input wire [31:0] weight_AWADDR,
    // Write Data Channel
    input wire weight_WVALID,
    output wire weight_WREADY,
    input wire [31:0] weight_WDATA,
    input wire [3:0] weight_WSTRB,

    // Write Response Channel
    output wire weight_BVALID,
    input wire weight_BREADY,
    output wire [1:0] weight_BRESP,
    // Read Address Channel
    input wire weight_ARVALID,
    output wire weight_ARREADY,
    input wire [31:0] weight_ARADDR,
    // Read Data Channel
    output wire weight_RVALID,
    input wire weight_RREADY,
    output wire [31:0] weight_RDATA,
    output wire [1:0] weight_RRESP);

    // Instantiate the wrapped kernel
    thresholding_axi #(
        // General algorithm parameters
        .input_FPARG(input_FPARG),
        .BIAS(BIAS),
        .THRESHOLDS_PATH(THRESHOLDS_PATH),
        .DEPTH_TRIGGER_URAM(DEPTH_TRIGGER_URAM),
        .DEPTH_TRIGGER_BRAM(DEPTH_TRIGGER_BRAM),
        .DEEP_PIPELINE(DEEP_PIPELINE),
        // AXI-Lite configuration parameters
        .USE_AXILITE(USE_AXILITE),
        // threshold datatype
        .T_WIDTH(T_WIDTH),
        // input interface parameters
        .input_BDIM(input_BDIM),
        .input_SDIM(input_SDIM),
        .input_WIDTH(input_WIDTH),
        .input_SIGNED(input_SIGNED),
        // output interface parameters
        .output_WIDTH(output_WIDTH)    ) thresholding_axi_inst (
        // Global control
        .ap_clk(ap_clk),
        .ap_rst_n(ap_rst_n),
        // input connections (from input)
        .input_tdata(input_TDATA),
        .input_tvalid(input_TVALID),
        .input_tready(input_TREADY),
        // output connections (to output)  
        .output_tdata(output_TDATA),
        .output_tvalid(output_TVALID),
        .output_tready(output_TREADY),
        // threshold connections (from/to weight)
        .threshold_AWVALID(weight_AWVALID),
        .threshold_AWREADY(weight_AWREADY),
        .threshold_AWADDR(weight_AWADDR),
        .threshold_WVALID(weight_WVALID),
        .threshold_WREADY(weight_WREADY),
        .threshold_WDATA(weight_WDATA),
        .threshold_WSTRB(weight_WSTRB),
        .threshold_BVALID(weight_BVALID),
        .threshold_BREADY(weight_BREADY),
        .threshold_BRESP(weight_BRESP),
        .threshold_ARVALID(weight_ARVALID),
        .threshold_ARREADY(weight_ARREADY),
        .threshold_ARADDR(weight_ARADDR),
        .threshold_RVALID(weight_RVALID),
        .threshold_RREADY(weight_RREADY),
        .threshold_RDATA(weight_RDATA),
        .threshold_RRESP(weight_RRESP)    );

endmodule // thresholding_axi_wrapper