name: 'Docker Cleanup'
description: 'Clean Docker container and build artifacts safely (scoped to current job)'

runs:
  using: 'composite'
  steps:
    - name: Clean Docker container resources
      shell: bash
      run: |
        echo "=== Docker container scoped cleanup ==="
        
        # Clean container and build artifacts
        if [ -x ./ctl-docker.sh ]; then
            # Use the clean command which handles both container and artifacts
            ./ctl-docker.sh clean
            echo "✓ Docker container and artifacts cleanup completed"
        else
            echo "No ctl-docker.sh script found, skipping cleanup"
        fi
        
        echo "Available space: $(df -h / | tail -1 | awk '{print $4}')"