name: 'Smithy Cleanup'
description: 'Clean Smithy container and build artifacts safely (scoped to current job)'

runs:
  using: 'composite'
  steps:
    - name: Clean Smithy container resources
      shell: bash
      run: |
        echo "=== Smithy scoped cleanup ==="
        
        # Clean container and build artifacts
        if [ -x ./smithy ]; then
            # Use the new clean command which handles both container and artifacts
            ./smithy clean
            echo "✓ Smithy container and artifacts cleanup completed"
        else
            echo "No smithy script found, skipping cleanup"
        fi
        
        echo "Available space: $(df -h / | tail -1 | awk '{print $4}')"