name: 'Smithy Cleanup'
description: 'Clean Smithy container resources safely (scoped to current job)'

runs:
  using: 'composite'
  steps:
    - name: Clean Smithy container resources
      shell: bash
      run: |
        echo "=== Smithy scoped cleanup ==="
        if [ -x ./smithy ]; then
            ./smithy cleanup
            echo "✓ Smithy container cleanup completed"
        else
            echo "No smithy script found, skipping cleanup"
        fi
        echo "Available space: $(df -h / | tail -1 | awk '{print $4}')"