name: 'Docker Save'
description: 'Save Docker image to artifact'
inputs:
  image-tag:
    description: 'Docker image tag to save'
    type: string
    required: true
  artifact-name:
    description: 'Artifact name for saved image'
    type: string
    default: 'docker-image'

runs:
  using: 'composite'
  steps:
    - name: Save Docker image
      shell: bash
      run: |
        echo "=== Saving Docker image ==="
        IMAGE_TAG="${{ inputs.image-tag }}"
        ARTIFACT_NAME="${{ inputs.artifact-name }}"
        
        # Verify image exists
        if ! docker images --format "{{.Repository}}:{{.Tag}}" | grep -q "^${IMAGE_TAG}$"; then
            echo "ERROR: Image ${IMAGE_TAG} not found"
            docker images
            exit 1
        fi
        
        # Save image to tar file
        mkdir -p /tmp/docker-artifacts
        docker save "${IMAGE_TAG}" | gzip > "/tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz"
        
        # Verify saved file
        if [ ! -f "/tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz" ]; then
            echo "ERROR: Failed to save image"
            exit 1
        fi
        
        FILE_SIZE=$(du -h "/tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz" | cut -f1)
        echo "✓ Image saved: ${FILE_SIZE}"
        echo "Artifact path: /tmp/docker-artifacts/${ARTIFACT_NAME}.tar.gz"